# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_login_dialog(object):
    def setupUi(self, login_dialog):
        login_dialog.setObjectName("login_dialog")
        login_dialog.resize(250, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(login_dialog.sizePolicy().hasHeightForWidth())
        login_dialog.setSizePolicy(sizePolicy)
        login_dialog.setMinimumSize(QtCore.QSize(250, 300))
        login_dialog.setMaximumSize(QtCore.QSize(250, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Windows/System32/@AppHelpToast.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        login_dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(login_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.input_login = QtWidgets.QLineEdit(login_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_login.sizePolicy().hasHeightForWidth())
        self.input_login.setSizePolicy(sizePolicy)
        self.input_login.setStyleSheet("")
        self.input_login.setText("")
        self.input_login.setMaxLength(100)
        self.input_login.setAlignment(QtCore.Qt.AlignCenter)
        self.input_login.setObjectName("input_login")
        self.gridLayout.addWidget(self.input_login, 2, 0, 1, 2)
        self.check_save_loginpwd = QtWidgets.QCheckBox(login_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_save_loginpwd.sizePolicy().hasHeightForWidth())
        self.check_save_loginpwd.setSizePolicy(sizePolicy)
        self.check_save_loginpwd.setTristate(False)
        self.check_save_loginpwd.setObjectName("check_save_loginpwd")
        self.gridLayout.addWidget(self.check_save_loginpwd, 6, 1, 1, 1)
        self.error_loginpwd = QtWidgets.QLabel(login_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_loginpwd.sizePolicy().hasHeightForWidth())
        self.error_loginpwd.setSizePolicy(sizePolicy)
        self.error_loginpwd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.error_loginpwd.setText("")
        self.error_loginpwd.setAlignment(QtCore.Qt.AlignCenter)
        self.error_loginpwd.setObjectName("error_loginpwd")
        self.gridLayout.addWidget(self.error_loginpwd, 4, 0, 1, 2)
        self.newlogin_button = QtWidgets.QPushButton(login_dialog)
        self.newlogin_button.setObjectName("newlogin_button")
        self.gridLayout.addWidget(self.newlogin_button, 9, 0, 1, 1)
        self.name_menu = QtWidgets.QLabel(login_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_menu.sizePolicy().hasHeightForWidth())
        self.name_menu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.name_menu.setFont(font)
        self.name_menu.setFocusPolicy(QtCore.Qt.NoFocus)
        self.name_menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.name_menu.setAutoFillBackground(False)
        self.name_menu.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.name_menu.setTextFormat(QtCore.Qt.AutoText)
        self.name_menu.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_menu.setObjectName("name_menu")
        self.gridLayout.addWidget(self.name_menu, 0, 1, 1, 1)
        self.newpwd_button = QtWidgets.QPushButton(login_dialog)
        self.newpwd_button.setObjectName("newpwd_button")
        self.gridLayout.addWidget(self.newpwd_button, 9, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(229, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 7, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(login_dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 8, 0, 1, 2)
        self.line = QtWidgets.QFrame(login_dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 2)
        self.input_pwd = QtWidgets.QLineEdit(login_dialog)
        self.input_pwd.setStyleSheet("")
        self.input_pwd.setText("")
        self.input_pwd.setMaxLength(100)
        self.input_pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_pwd.setAlignment(QtCore.Qt.AlignCenter)
        self.input_pwd.setObjectName("input_pwd")
        self.gridLayout.addWidget(self.input_pwd, 3, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(login_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setContentsMargins(0, 6, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 2, 1, 1)
        self.login_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.login_button.sizePolicy().hasHeightForWidth())
        self.login_button.setSizePolicy(sizePolicy)
        self.login_button.setObjectName("login_button")
        self.gridLayout_3.addWidget(self.login_button, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 5, 0, 1, 2)
        self.line_3 = QtWidgets.QFrame(login_dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 10, 0, 1, 2)
        self.label_log = QtWidgets.QLabel(login_dialog)
        self.label_log.setText("")
        self.label_log.setObjectName("label_log")
        self.gridLayout.addWidget(self.label_log, 11, 0, 1, 2)

        self.retranslateUi(login_dialog)
        QtCore.QMetaObject.connectSlotsByName(login_dialog)

    def retranslateUi(self, login_dialog):
        _translate = QtCore.QCoreApplication.translate
        login_dialog.setWindowTitle(_translate("login_dialog", "peMI"))
        self.input_login.setToolTip(_translate("login_dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.check_save_loginpwd.setText(_translate("login_dialog", "Запомнить"))
        self.newlogin_button.setText(_translate("login_dialog", "Сменить логин"))
        self.name_menu.setText(_translate("login_dialog", "Вход"))
        self.newpwd_button.setText(_translate("login_dialog", "Сменить пароль"))
        self.login_button.setText(_translate("login_dialog", "Вход"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_dialog = QtWidgets.QDialog()
    ui = Ui_login_dialog()
    ui.setupUi(login_dialog)
    login_dialog.show()
    sys.exit(app.exec_())

