# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'replace_login.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_replace_login_dialog(object):
    def setupUi(self, replace_login_dialog):
        replace_login_dialog.setObjectName("replace_login_dialog")
        replace_login_dialog.resize(250, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(replace_login_dialog.sizePolicy().hasHeightForWidth())
        replace_login_dialog.setSizePolicy(sizePolicy)
        replace_login_dialog.setMinimumSize(QtCore.QSize(250, 300))
        replace_login_dialog.setMaximumSize(QtCore.QSize(250, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Windows/System32/@AppHelpToast.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        replace_login_dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(replace_login_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.name_menu = QtWidgets.QLabel(replace_login_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_menu.sizePolicy().hasHeightForWidth())
        self.name_menu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.name_menu.setFont(font)
        self.name_menu.setFocusPolicy(QtCore.Qt.NoFocus)
        self.name_menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.name_menu.setAutoFillBackground(False)
        self.name_menu.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.name_menu.setTextFormat(QtCore.Qt.AutoText)
        self.name_menu.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_menu.setObjectName("name_menu")
        self.gridLayout.addWidget(self.name_menu, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(replace_login_dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 2)
        self.input_oldlogin = QtWidgets.QLineEdit(replace_login_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_oldlogin.sizePolicy().hasHeightForWidth())
        self.input_oldlogin.setSizePolicy(sizePolicy)
        self.input_oldlogin.setStyleSheet("")
        self.input_oldlogin.setMaxLength(100)
        self.input_oldlogin.setAlignment(QtCore.Qt.AlignCenter)
        self.input_oldlogin.setObjectName("input_oldlogin")
        self.gridLayout.addWidget(self.input_oldlogin, 2, 0, 1, 2)
        self.input_pwd = QtWidgets.QLineEdit(replace_login_dialog)
        self.input_pwd.setMaxLength(100)
        self.input_pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_pwd.setAlignment(QtCore.Qt.AlignCenter)
        self.input_pwd.setObjectName("input_pwd")
        self.gridLayout.addWidget(self.input_pwd, 3, 0, 1, 2)
        self.message_newlogin = QtWidgets.QLabel(replace_login_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_newlogin.sizePolicy().hasHeightForWidth())
        self.message_newlogin.setSizePolicy(sizePolicy)
        self.message_newlogin.setMaximumSize(QtCore.QSize(16777215, 200))
        self.message_newlogin.setSizeIncrement(QtCore.QSize(20, 20))
        self.message_newlogin.setBaseSize(QtCore.QSize(10, 20))
        self.message_newlogin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.message_newlogin.setTextFormat(QtCore.Qt.AutoText)
        self.message_newlogin.setScaledContents(False)
        self.message_newlogin.setAlignment(QtCore.Qt.AlignCenter)
        self.message_newlogin.setObjectName("message_newlogin")
        self.gridLayout.addWidget(self.message_newlogin, 4, 0, 1, 2)
        self.input_newlogin = QtWidgets.QLineEdit(replace_login_dialog)
        self.input_newlogin.setStyleSheet("")
        self.input_newlogin.setMaxLength(100)
        self.input_newlogin.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.input_newlogin.setAlignment(QtCore.Qt.AlignCenter)
        self.input_newlogin.setObjectName("input_newlogin")
        self.gridLayout.addWidget(self.input_newlogin, 5, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(replace_login_dialog)
        self.groupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setToolTipDuration(-1)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setTitle("")
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_2.setContentsMargins(0, 6, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.save_newlogin_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.save_newlogin_button.sizePolicy().hasHeightForWidth())
        self.save_newlogin_button.setSizePolicy(sizePolicy)
        self.save_newlogin_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.save_newlogin_button.setAutoFillBackground(False)
        self.save_newlogin_button.setFlat(False)
        self.save_newlogin_button.setObjectName("save_newlogin_button")
        self.gridLayout_2.addWidget(self.save_newlogin_button, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.back_button = QtWidgets.QPushButton(self.groupBox)
        self.back_button.setObjectName("back_button")
        self.gridLayout_2.addWidget(self.back_button, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 7, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(replace_login_dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 8, 0, 1, 2)
        self.label_log = QtWidgets.QLabel(replace_login_dialog)
        self.label_log.setEnabled(True)
        self.label_log.setText("")
        self.label_log.setObjectName("label_log")
        self.gridLayout.addWidget(self.label_log, 9, 0, 1, 2)

        self.retranslateUi(replace_login_dialog)
        QtCore.QMetaObject.connectSlotsByName(replace_login_dialog)

    def retranslateUi(self, replace_login_dialog):
        _translate = QtCore.QCoreApplication.translate
        replace_login_dialog.setWindowTitle(_translate("replace_login_dialog", "peMI"))
        self.name_menu.setText(_translate("replace_login_dialog", "Смена логина"))
        self.input_oldlogin.setToolTip(_translate("replace_login_dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.input_oldlogin.setText(_translate("replace_login_dialog", "Логин"))
        self.input_pwd.setText(_translate("replace_login_dialog", "Пароль"))
        self.message_newlogin.setText(_translate("replace_login_dialog", "<html><head/><body><p align=\"center\">Формат логина:<br/><span style=\" font-style:italic;\">любой_набор_символов@домен.com</span></p></body></html>"))
        self.input_newlogin.setText(_translate("replace_login_dialog", "Новый логин"))
        self.save_newlogin_button.setText(_translate("replace_login_dialog", "Сохранить"))
        self.back_button.setText(_translate("replace_login_dialog", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    replace_login_dialog = QtWidgets.QDialog()
    ui = Ui_replace_login_dialog()
    ui.setupUi(replace_login_dialog)
    replace_login_dialog.show()
    sys.exit(app.exec_())

