# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'replace_pass.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_replace_pass_window(object):
    def setupUi(self, replace_pass_window):
        replace_pass_window.setObjectName("replace_pass_window")
        replace_pass_window.setEnabled(True)
        replace_pass_window.resize(250, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(replace_pass_window.sizePolicy().hasHeightForWidth())
        replace_pass_window.setSizePolicy(sizePolicy)
        replace_pass_window.setMinimumSize(QtCore.QSize(250, 300))
        replace_pass_window.setMaximumSize(QtCore.QSize(250, 300))
        replace_pass_window.setSizeIncrement(QtCore.QSize(0, 0))
        replace_pass_window.setTabletTracking(False)
        replace_pass_window.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        replace_pass_window.setAcceptDrops(False)
        replace_pass_window.setLayoutDirection(QtCore.Qt.LeftToRight)
        replace_pass_window.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        replace_pass_window.setTabShape(QtWidgets.QTabWidget.Rounded)
        replace_pass_window.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(replace_pass_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 12, 0, 1, 2)
        self.name_menu = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_menu.sizePolicy().hasHeightForWidth())
        self.name_menu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.name_menu.setFont(font)
        self.name_menu.setFocusPolicy(QtCore.Qt.NoFocus)
        self.name_menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.name_menu.setAutoFillBackground(False)
        self.name_menu.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.name_menu.setTextFormat(QtCore.Qt.AutoText)
        self.name_menu.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_menu.setObjectName("name_menu")
        self.gridLayout.addWidget(self.name_menu, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 2)
        self.message_newpwd = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_newpwd.sizePolicy().hasHeightForWidth())
        self.message_newpwd.setSizePolicy(sizePolicy)
        self.message_newpwd.setMaximumSize(QtCore.QSize(16777215, 200))
        self.message_newpwd.setSizeIncrement(QtCore.QSize(20, 20))
        self.message_newpwd.setBaseSize(QtCore.QSize(10, 20))
        self.message_newpwd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.message_newpwd.setTextFormat(QtCore.Qt.AutoText)
        self.message_newpwd.setScaledContents(False)
        self.message_newpwd.setAlignment(QtCore.Qt.AlignCenter)
        self.message_newpwd.setObjectName("message_newpwd")
        self.gridLayout.addWidget(self.message_newpwd, 7, 0, 1, 2)
        self.input_login = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_login.sizePolicy().hasHeightForWidth())
        self.input_login.setSizePolicy(sizePolicy)
        self.input_login.setStyleSheet("")
        self.input_login.setMaxLength(100)
        self.input_login.setAlignment(QtCore.Qt.AlignCenter)
        self.input_login.setObjectName("input_login")
        self.gridLayout.addWidget(self.input_login, 3, 0, 1, 2)
        self.message_oldpwd = QtWidgets.QLabel(self.centralwidget)
        self.message_oldpwd.setAlignment(QtCore.Qt.AlignCenter)
        self.message_oldpwd.setObjectName("message_oldpwd")
        self.gridLayout.addWidget(self.message_oldpwd, 4, 0, 1, 2)
        self.input_oldpwd = QtWidgets.QLineEdit(self.centralwidget)
        self.input_oldpwd.setMaxLength(100)
        self.input_oldpwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_oldpwd.setAlignment(QtCore.Qt.AlignCenter)
        self.input_oldpwd.setObjectName("input_oldpwd")
        self.gridLayout.addWidget(self.input_oldpwd, 5, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 10, 0, 1, 2)
        self.input_newpwd = QtWidgets.QLineEdit(self.centralwidget)
        self.input_newpwd.setStyleSheet("")
        self.input_newpwd.setMaxLength(100)
        self.input_newpwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_newpwd.setAlignment(QtCore.Qt.AlignCenter)
        self.input_newpwd.setObjectName("input_newpwd")
        self.gridLayout.addWidget(self.input_newpwd, 8, 0, 1, 2)
        self.name_program = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_program.sizePolicy().hasHeightForWidth())
        self.name_program.setSizePolicy(sizePolicy)
        self.name_program.setObjectName("name_program")
        self.gridLayout.addWidget(self.name_program, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setToolTipDuration(-1)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setTitle("")
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_2.setContentsMargins(0, 6, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.save_newpwd_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.save_newpwd_button.sizePolicy().hasHeightForWidth())
        self.save_newpwd_button.setSizePolicy(sizePolicy)
        self.save_newpwd_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.save_newpwd_button.setAutoFillBackground(False)
        self.save_newpwd_button.setFlat(False)
        self.save_newpwd_button.setObjectName("save_newpwd_button")
        self.gridLayout_2.addWidget(self.save_newpwd_button, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.back_main_button = QtWidgets.QPushButton(self.groupBox)
        self.back_main_button.setObjectName("back_main_button")
        self.gridLayout_2.addWidget(self.back_main_button, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 11, 0, 1, 2)
        self.label_log = QtWidgets.QLabel(self.centralwidget)
        self.label_log.setObjectName("label_log")
        self.gridLayout.addWidget(self.label_log, 13, 0, 1, 2)
        replace_pass_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(replace_pass_window)
        self.statusbar.setObjectName("statusbar")
        replace_pass_window.setStatusBar(self.statusbar)

        self.retranslateUi(replace_pass_window)
        QtCore.QMetaObject.connectSlotsByName(replace_pass_window)

    def retranslateUi(self, replace_pass_window):
        _translate = QtCore.QCoreApplication.translate
        replace_pass_window.setWindowTitle(_translate("replace_pass_window", "PMS Смена пароля"))
        self.name_menu.setText(_translate("replace_pass_window", "Смена пароля"))
        self.message_newpwd.setText(_translate("replace_pass_window", "<html><head/><body><p align=\"center\">Кровь девствиницы,</p><p align=\"center\">китайские символы и прочая херь</p></body></html>"))
        self.input_login.setToolTip(_translate("replace_pass_window", "<html><head/><body><p><br/></p></body></html>"))
        self.input_login.setText(_translate("replace_pass_window", "Логин"))
        self.message_oldpwd.setText(_translate("replace_pass_window", "Введите старый пароль"))
        self.input_oldpwd.setText(_translate("replace_pass_window", "Пароль"))
        self.input_newpwd.setText(_translate("replace_pass_window", "Пароль"))
        self.name_program.setText(_translate("replace_pass_window", "Название проги"))
        self.save_newpwd_button.setText(_translate("replace_pass_window", "Сохранить"))
        self.back_main_button.setText(_translate("replace_pass_window", "Назад"))
        self.label_log.setText(_translate("replace_pass_window", "Log"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    replace_pass_window = QtWidgets.QMainWindow()
    ui = Ui_replace_pass_window()
    ui.setupUi(replace_pass_window)
    replace_pass_window.show()
    sys.exit(app.exec_())

