# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1023, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Windows/System32/@AppHelpToast.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.del_worker = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_worker.sizePolicy().hasHeightForWidth())
        self.del_worker.setSizePolicy(sizePolicy)
        self.del_worker.setMinimumSize(QtCore.QSize(75, 0))
        self.del_worker.setMaximumSize(QtCore.QSize(75, 16777215))
        self.del_worker.setObjectName("del_worker")
        self.gridLayout_2.addWidget(self.del_worker, 2, 4, 1, 1)
        self.workers_table = QtWidgets.QTableWidget(self.tab)
        self.workers_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.workers_table.setGridStyle(QtCore.Qt.SolidLine)
        self.workers_table.setObjectName("workers_table")
        self.workers_table.setColumnCount(5)
        self.workers_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.workers_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.workers_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.workers_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.workers_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.workers_table.setHorizontalHeaderItem(4, item)
        self.gridLayout_2.addWidget(self.workers_table, 1, 0, 1, 6)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 3)
        self.new_inproject = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_inproject.sizePolicy().hasHeightForWidth())
        self.new_inproject.setSizePolicy(sizePolicy)
        self.new_inproject.setMinimumSize(QtCore.QSize(120, 20))
        self.new_inproject.setMaximumSize(QtCore.QSize(150, 16777215))
        self.new_inproject.setBaseSize(QtCore.QSize(120, 0))
        self.new_inproject.setObjectName("new_inproject")
        self.gridLayout_2.addWidget(self.new_inproject, 2, 8, 1, 1)
        self.add_worker = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_worker.sizePolicy().hasHeightForWidth())
        self.add_worker.setSizePolicy(sizePolicy)
        self.add_worker.setMinimumSize(QtCore.QSize(75, 0))
        self.add_worker.setMaximumSize(QtCore.QSize(75, 16777215))
        self.add_worker.setObjectName("add_worker")
        self.gridLayout_2.addWidget(self.add_worker, 2, 5, 1, 1)
        self.del_inproject = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_inproject.sizePolicy().hasHeightForWidth())
        self.del_inproject.setSizePolicy(sizePolicy)
        self.del_inproject.setObjectName("del_inproject")
        self.gridLayout_2.addWidget(self.del_inproject, 4, 8, 1, 1)
        self.save_workers = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_workers.sizePolicy().hasHeightForWidth())
        self.save_workers.setSizePolicy(sizePolicy)
        self.save_workers.setMinimumSize(QtCore.QSize(120, 0))
        self.save_workers.setMaximumSize(QtCore.QSize(120, 16777215))
        self.save_workers.setSizeIncrement(QtCore.QSize(0, 0))
        self.save_workers.setBaseSize(QtCore.QSize(0, 0))
        self.save_workers.setObjectName("save_workers")
        self.gridLayout_2.addWidget(self.save_workers, 2, 0, 1, 1)
        self.project_box = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.project_box.sizePolicy().hasHeightForWidth())
        self.project_box.setSizePolicy(sizePolicy)
        self.project_box.setMinimumSize(QtCore.QSize(110, 20))
        self.project_box.setMaximumSize(QtCore.QSize(150, 20))
        self.project_box.setObjectName("project_box")
        self.gridLayout_2.addWidget(self.project_box, 2, 7, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 6, 1, 1)
        self.current_projects_table = QtWidgets.QTableWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_projects_table.sizePolicy().hasHeightForWidth())
        self.current_projects_table.setSizePolicy(sizePolicy)
        self.current_projects_table.setMinimumSize(QtCore.QSize(300, 0))
        self.current_projects_table.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.current_projects_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.current_projects_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.current_projects_table.setGridStyle(QtCore.Qt.SolidLine)
        self.current_projects_table.setObjectName("current_projects_table")
        self.current_projects_table.setColumnCount(2)
        self.current_projects_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.current_projects_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.current_projects_table.setHorizontalHeaderItem(1, item)
        self.current_projects_table.horizontalHeader().setCascadingSectionResizes(False)
        self.current_projects_table.horizontalHeader().setDefaultSectionSize(120)
        self.current_projects_table.horizontalHeader().setMinimumSectionSize(39)
        self.current_projects_table.horizontalHeader().setSortIndicatorShown(False)
        self.current_projects_table.horizontalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.current_projects_table, 1, 6, 1, 3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.add_project = QtWidgets.QPushButton(self.tab_2)
        self.add_project.setObjectName("add_project")
        self.gridLayout_3.addWidget(self.add_project, 2, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 2, 0, 1, 1)
        self.projects_table = QtWidgets.QTableWidget(self.tab_2)
        self.projects_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.projects_table.setObjectName("projects_table")
        self.projects_table.setColumnCount(2)
        self.projects_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.projects_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.projects_table.setHorizontalHeaderItem(1, item)
        self.projects_table.horizontalHeader().setDefaultSectionSize(120)
        self.gridLayout_3.addWidget(self.projects_table, 0, 0, 1, 5)
        self.del_project = QtWidgets.QPushButton(self.tab_2)
        self.del_project.setObjectName("del_project")
        self.gridLayout_3.addWidget(self.del_project, 2, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 2, 2, 1, 1)
        self.save_projects = QtWidgets.QPushButton(self.tab_2)
        self.save_projects.setObjectName("save_projects")
        self.gridLayout_3.addWidget(self.save_projects, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Разработка программного обеспечения"))
        self.del_worker.setText(_translate("MainWindow", "Удалить"))
        item = self.workers_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Email"))
        item = self.workers_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Фамилия"))
        item = self.workers_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Имя"))
        item = self.workers_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Отчество"))
        item = self.workers_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Должность"))
        self.new_inproject.setText(_translate("MainWindow", "Назначить проект"))
        self.add_worker.setText(_translate("MainWindow", "Добавить"))
        self.del_inproject.setText(_translate("MainWindow", "Убрать с проекта"))
        self.save_workers.setText(_translate("MainWindow", "Сохранить изменения"))
        item = self.current_projects_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Название продукта"))
        item = self.current_projects_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Срок сдачи"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Работники"))
        self.add_project.setText(_translate("MainWindow", "Добавить"))
        item = self.projects_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Название продукта"))
        item = self.projects_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Срок сдачи"))
        self.del_project.setText(_translate("MainWindow", "Удалить"))
        self.save_projects.setText(_translate("MainWindow", "Сохранить изменения"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Проекты"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

