# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_inproject_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_add_inproject_dialog(object):
    def setupUi(self, add_inproject_dialog):
        add_inproject_dialog.setObjectName("add_inproject_dialog")
        add_inproject_dialog.setWindowModality(QtCore.Qt.NonModal)
        add_inproject_dialog.resize(350, 275)
        add_inproject_dialog.setMinimumSize(QtCore.QSize(350, 275))
        add_inproject_dialog.setMaximumSize(QtCore.QSize(350, 275))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/title.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        add_inproject_dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(add_inproject_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.add_button = QtWidgets.QPushButton(add_inproject_dialog)
        self.add_button.setEnabled(False)
        self.add_button.setObjectName("add_button")
        self.gridLayout.addWidget(self.add_button, 3, 1, 1, 1)
        self.cancel_button = QtWidgets.QPushButton(add_inproject_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_button.sizePolicy().hasHeightForWidth())
        self.cancel_button.setSizePolicy(sizePolicy)
        self.cancel_button.setObjectName("cancel_button")
        self.gridLayout.addWidget(self.cancel_button, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.listWidget_inproject = QtWidgets.QListWidget(add_inproject_dialog)
        self.listWidget_inproject.setObjectName("listWidget_inproject")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_inproject.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_inproject.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_inproject.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_inproject.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_inproject.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_inproject.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_inproject.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_inproject.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_inproject.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_inproject.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_inproject.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_inproject.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_inproject.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_inproject.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_inproject.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_inproject.addItem(item)
        self.gridLayout.addWidget(self.listWidget_inproject, 2, 0, 1, 3)
        self.label_dialog_inpoject = QtWidgets.QLabel(add_inproject_dialog)
        self.label_dialog_inpoject.setObjectName("label_dialog_inpoject")
        self.gridLayout.addWidget(self.label_dialog_inpoject, 0, 0, 1, 3)
        self.line = QtWidgets.QFrame(add_inproject_dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 3)

        self.retranslateUi(add_inproject_dialog)
        QtCore.QMetaObject.connectSlotsByName(add_inproject_dialog)

    def retranslateUi(self, add_inproject_dialog):
        _translate = QtCore.QCoreApplication.translate
        add_inproject_dialog.setWindowTitle(_translate("add_inproject_dialog", "Добавление прользователя в проект"))
        self.add_button.setText(_translate("add_inproject_dialog", "Добавить"))
        self.cancel_button.setText(_translate("add_inproject_dialog", "Отмена"))
        self.listWidget_inproject.setSortingEnabled(True)
        __sortingEnabled = self.listWidget_inproject.isSortingEnabled()
        self.listWidget_inproject.setSortingEnabled(False)
        item = self.listWidget_inproject.item(0)
        item.setText(_translate("add_inproject_dialog", "New Item"))
        item = self.listWidget_inproject.item(1)
        item.setText(_translate("add_inproject_dialog", "New Item"))
        item = self.listWidget_inproject.item(2)
        item.setText(_translate("add_inproject_dialog", "New Item"))
        item = self.listWidget_inproject.item(3)
        item.setText(_translate("add_inproject_dialog", "New Item"))
        item = self.listWidget_inproject.item(4)
        item.setText(_translate("add_inproject_dialog", "New Item"))
        item = self.listWidget_inproject.item(5)
        item.setText(_translate("add_inproject_dialog", "New Item"))
        item = self.listWidget_inproject.item(6)
        item.setText(_translate("add_inproject_dialog", "New Item"))
        item = self.listWidget_inproject.item(7)
        item.setText(_translate("add_inproject_dialog", "New Item"))
        item = self.listWidget_inproject.item(8)
        item.setText(_translate("add_inproject_dialog", "New Item"))
        item = self.listWidget_inproject.item(9)
        item.setText(_translate("add_inproject_dialog", "New Item"))
        item = self.listWidget_inproject.item(10)
        item.setText(_translate("add_inproject_dialog", "New Item"))
        item = self.listWidget_inproject.item(11)
        item.setText(_translate("add_inproject_dialog", "New Item"))
        item = self.listWidget_inproject.item(12)
        item.setText(_translate("add_inproject_dialog", "New Item"))
        item = self.listWidget_inproject.item(13)
        item.setText(_translate("add_inproject_dialog", "New Item"))
        item = self.listWidget_inproject.item(14)
        item.setText(_translate("add_inproject_dialog", "New Item"))
        item = self.listWidget_inproject.item(15)
        item.setText(_translate("add_inproject_dialog", "New Item"))
        self.listWidget_inproject.setSortingEnabled(__sortingEnabled)
        self.label_dialog_inpoject.setText(_translate("add_inproject_dialog", "Выберете проект"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_inproject_dialog = QtWidgets.QDialog()
    ui = Ui_add_inproject_dialog()
    ui.setupUi(add_inproject_dialog)
    add_inproject_dialog.show()
    sys.exit(app.exec_())

